kodi-pvr/pvr.vdr.vnsi

pvr.vdr.vnsi/addon.xml, src/VNSIAdmin.cpp, src/VNSIAdmin.h, src/client.cpp, src/client.h
=> sync to API changes

pvr.vdr.vnsi/addon.xml, src/VNSIData.cpp
=> sync to pvr API 1.9.6

pvr.vdr.vnsi/addon.xml
=> bump version to 1.10.6

pvr.vdr.vnsi/addon.xml
Add-on part of https://github.com/xbmc/xbmc/pull/7536
Code is already in place
=> Bump add-on for PVR API 2.1.0 (already implemented, let's use it)

pvr.vdr.vnsi/addon.xml.in
Add-on part of https://github.com/xbmc/xbmc/pull/7570
=> Automatically fill in platform and library name

pvr.vdr.vnsi/addon.xml.in, src/client.cpp
This PR implements all changes needed to properly support PVR Addon API v4.0.0, including a PVR addon micro version bump.
Details can be found here: https://github.com/xbmc/xbmc/pull/8005
=> Update to PVR addon API v4.0.0

pvr.vdr.vnsi/addon.xml.in, src/VNSIData.cpp
see title, plotOutline seems to be depreciated
=> epg: fill episodeName with short text

src/VNSIAdmin.cpp, src/VNSIChannelScan.cpp, src/VNSIData.cpp, src/VNSIDemux.cpp, src/VNSISession.cpp, src/responsepacket.cpp, src/responsepacket.h
Fix various crash bugs.
This whole plugin is a fractal of crash bugs. There are dozens of crash bugs left; everywhere I look, new ones unfold. It's a big mess. I will address more of those bugs later, after this branch is merged.
=> Crash fixes

pvr.vdr.vnsi/addon.xml.in
Addon side of https://github.com/xbmc/xbmc/pull/8494
=> Updated to GUI API v5.10.0

pvr.vdr.vnsi/addon.xml.in, src/VNSIData.cpp
fix: https://github.com/FernetMenta/vdr-plugin-vnsiserver/issues/33
=> replace colons in timer file names

src/EGLHelpers/VisMatrixGLES.cpp
=> [arm64] - fixed compilation for arm64

pvr.vdr.vnsi/addon.xml.in, src/VNSIDemux.cpp
=> consider cient setting for timeshift

pvr.vdr.vnsi/addon.xml.in
fixup after #53
@FernetMenta do you want me to bump addon version again ?
=> depends on pvr api 4.2.0

pvr.vdr.vnsi/addon.xml.in, src/VNSIData.cpp, src/VNSIDemux.cpp, src/client.cpp
For details refer to https://github.com/xbmc/xbmc/pull/8736
Before this PR can go in, https://github.com/xbmc/xbmc/pull/8736 must be merged.
=> Implement PVR API 5.0.0

src/VNSIDemux.cpp, src/VNSIDemux.h
=> adapt to pvr api change in stream props

pvr.vdr.vnsi/resources/skins/skin.estuary/1080i/Admin.xml
because of https://github.com/xbmc/xbmc/pull/9114
=> [skin] adapt to recent include attribute renaming

pvr.vdr.vnsi/addon.xml.in, src/VNSIDemux.h, src/client.cpp, src/client.h, src/tools.h
https://github.com/xbmc/xbmc/pull/9804 and https://github.com/xbmc/xbmc/pull/9671 for reference
=> Fix includes

pvr.vdr.vnsi/addon.xml.in, pvr.vdr.vnsi/resources/settings.xml, src/client.cpp
see title
@glenvt18 this should fix the issue with prio always set to -1
=> fix addon settings prio and port

pvr.vdr.vnsi/addon.xml.in, src/client.cpp
=> send wol on system resume

pvr.vdr.vnsi/resources/skins/skin.estuary/1080i/Admin.xml
- code cleanup
- fix wrong headline
- button adjustments, alignment
=> [skin] some fixes for estuary Admin.xml
